Controle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Estoque.urls', namespace='Estoque')),
]

urlpatterns+= static(settings.STATIC_URL, document_root  = settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root  = settings.MEDIA_ROOT)

Estoque/urls.py
from django.urls import path, include
from .views import *

app_name = 'Estoque'

urlpatterns = [
    path('', HomePage.as_view(), name='homepage'),
    path('novoitem/', NovoItem.as_view(), name='novo_item'),
    path('entradas/', entradas, name='entradas'),
    path('saidas/', saidas, name='saidas'),
    path('statusestoque/', status, name='status'),
    path('estoques/', estoque, name='estoques'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="pt-br">
<head>
    <title>
        {% block title %}

        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <script src="{% static 'js/custom.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body onload="verificarSituacao()">
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/nav.html
{% load static %}

<nav class="navbar bg-body-tertiary fixed-top nav">
  <script src="{% static 'js/custom.js' %}"></script>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Estoque:homepage' %}">
      <img src="{% static 'image/Logo.jpg' %}" class="logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel"><img src="{% static 'image/Logo.jpg' %}" class="logo" alt="Controle de Estoque JL"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Estoque:novo_item' %}">Novo Item <img src="{% static 'css/image/registro.png' %}" class="iconesNav"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Estoque:entradas' %}">Entradas <img src="{% static 'css/image/entrada.png' %}" class="iconesNav"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Estoque:saidas' %}">Saídas <img src="{% static 'css/image/saida.png' %}" class="iconesNav"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Estoque:estoques' %}">Estoque <img src="{% static 'css/image/estoque.png' %}" class="iconesNav"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Estoque:status' %}">Status Estoque <img src="{% static 'css/image/caixa.png' %}" class="iconesNav"></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>